version: "3.8"

volumes:
  postgres-data: {}
  seq-data: {}

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=storify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  
  seq:
    container_name: seq
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    volumes:
      - seq-data:/data